# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class J4c < Formula
  desc "Non-interactive Jira CLI for AI agents"
  homepage "https://github.com/fwojciec/jira4claude"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fwojciec/jira4claude/releases/download/v0.2.0/jira4claude_Darwin_x86_64.tar.gz"
      sha256 "36be8d544475e30fd878951243a7447f4e178cce3a582bd6a76cffe9fae2e1f6"

      def install
        bin.install "j4c"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fwojciec/jira4claude/releases/download/v0.2.0/jira4claude_Darwin_arm64.tar.gz"
      sha256 "20b0bd06055a995831d610030510df81cea3205cef489c3244a9710e62b8b7db"

      def install
        bin.install "j4c"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fwojciec/jira4claude/releases/download/v0.2.0/jira4claude_Linux_x86_64.tar.gz"
      sha256 "bbafd495b63d9d4cdacc719b2206592bac97db7683d55783bfc7e2ccf4ef507b"
      def install
        bin.install "j4c"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fwojciec/jira4claude/releases/download/v0.2.0/jira4claude_Linux_arm64.tar.gz"
      sha256 "3fd8bdbfbad0fee802c618deac0bfd3ff88c98fa721738bec0a49c199dd64b84"
      def install
        bin.install "j4c"
      end
    end
  end

  test do
    system "#{bin}/j4c", "--version"
  end
end
